// Generated by Framer (8b16de8)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ComponentViewportProvider,
    ControlType,
    cx,
    forwardLoader,
    getFonts,
    SmartComponentScopedContainer,
    useActiveVariantCallback,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS,
    withFX,
    withVariantAppearEffect
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import WorkList from "https://framerusercontent.com/modules/b0I9lC60NWuVuybTHEX7/UEd5aFQeqJt8aPfpnMXC/hZ_InEJqT.js";
import WorkSwitch from "https://framerusercontent.com/modules/sItYyUxo6Z1tpioxyxW6/0HTFBu7zAUJA4Cc3zg1M/I3FYJ2PFv.js";
import WorkColumn from "https://framerusercontent.com/modules/SzapJEScfMiMkapcZsIW/mRruNujnrxCxXolcaTkt/MKxXJ_5KD.js";
const WorkColumnFonts = getFonts(WorkColumn);
const WorkColumnWithVariantAppearEffect = withVariantAppearEffect(WorkColumn);
const WorkListFonts = getFonts(WorkList);
const WorkSwitchFonts = getFonts(WorkSwitch);
const MotionDivWithFX = withFX(motion.div);
const cycleOrder = ["h3UYmb6_l", "SKuxYYyD6", "uDo_SmVsc"];
const serializationHash = "framer-xZCBi";
const variantClassNames = {
    h3UYmb6_l: "framer-v-1nuaa0m",
    SKuxYYyD6: "framer-v-160c0sb",
    uDo_SmVsc: "framer-v-19er1hx"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const mUzwET1Ix = undefined;
const LHfLHr6TF = undefined;
const fiyb2IThv = undefined;
const nWdiJ6BDt = undefined;
const f_jVoJ8Dh = undefined;
const ZAVV92XrN = undefined;
const GMhjAY4Gg = "https://cypherconnect-new-prod.web.app/";
const e6r1XTL03 = undefined;
const KX7KRKmIM = undefined;
const PUjhBs7tJ = undefined;
const UHHeeF5QI = undefined;
const HaQQ2BJWM = undefined;
const SeAgW_Svg = undefined;
const nN3KCdL8v = undefined;
const pX4YVkI63 = undefined;
const JhRen4I_0 = undefined;
const fhhHabEMA = undefined;
const IszbDCIOc = undefined;
const yHfqSNGHO = undefined;
const QACZQTXxi = undefined;
const HjzPlJrPN = undefined;
const IuDRA_bKL = undefined;
const E0RL6e4ta = undefined;
const X_RoM5kx7 = undefined;
const sT8NgyIwH = undefined;
const setnN3KCdL8v = undefined;
const setpX4YVkI63 = undefined;
const setJhRen4I_0 = undefined;
const setfhhHabEMA = undefined;
const setIszbDCIOc = undefined;
const setyHfqSNGHO = undefined;
const transition1 = {
    bounce: 0,
    delay: 0,
    duration: 1,
    type: "spring"
};
const toResponsiveImage = value => {
    if (typeof value === "object" && value !== null && typeof value.src === "string") {
        return value;
    }
    return typeof value === "string" ? {
        src: value
    } : undefined;
};
const matchVariant = (...args) => {
    for (const arg of args) {
        if (arg && typeof arg === "string") return arg;
    }
    return undefined;
};
const animation = {
    opacity: 0,
    rotate: 0,
    rotateX: 0,
    rotateY: 0,
    scale: 1,
    skewX: 0,
    skewY: 0,
    x: 0,
    y: 80
};
const transition2 = {
    bounce: 0,
    delay: 0,
    duration: 1.2,
    type: "spring"
};
const animation1 = {
    opacity: 0,
    rotate: 0,
    rotateX: 0,
    rotateY: 0,
    scale: 1,
    skewX: 0,
    skewY: 0,
    transition: transition2,
    x: 0,
    y: 80
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const humanReadableVariantMap = {
    Column: "h3UYmb6_l",
    List: "SKuxYYyD6",
    Phone: "uDo_SmVsc"
};
const Variants = motion.create(React.Fragment);
const useStateVariable = (externalState, setExternalState) => {
    const [internalState, setInternalState] = React.useState(externalState);
    const [previousExternalState, setPreviousExternalState] = React.useState(externalState);
    if (setExternalState) {
        return [externalState, setExternalState];
    }
    if (externalState !== previousExternalState) {
        setInternalState(externalState);
        setPreviousExternalState(externalState);
    }
    return [internalState, setInternalState];
};
const getProps = ({
    cursor,
    height,
    id,
    image1,
    image2,
    image3,
    image4,
    image5,
    image6,
    link1,
    link2,
    link3,
    link4,
    link5,
    link6,
    title1,
    title2,
    title3,
    title4,
    title5,
    title6,
    width,
    ...props
}) => {
    return { ...props,
        e6r1XTL03: image1 ? ? props.e6r1XTL03 ? ? {
            pixelHeight: 850,
            pixelWidth: 1144,
            src: "https://framerusercontent.com/images/MRNZnm8oX4TN995oGo4jWqPreA.png?width=1144&height=850",
            srcSet: "https://framerusercontent.com/images/MRNZnm8oX4TN995oGo4jWqPreA.png?scale-down-to=512&width=1144&height=850 512w,https://framerusercontent.com/images/MRNZnm8oX4TN995oGo4jWqPreA.png?scale-down-to=1024&width=1144&height=850 1024w,https://framerusercontent.com/images/MRNZnm8oX4TN995oGo4jWqPreA.png?width=1144&height=850 1144w"
        },
        f_jVoJ8Dh: link4 ? ? props.f_jVoJ8Dh,
        fhhHabEMA: title4 ? ? props.fhhHabEMA ? ? "WEBSITE DESIGN",
        fiyb2IThv: link2 ? ? props.fiyb2IThv,
        GMhjAY4Gg: link6 ? ? props.GMhjAY4Gg,
        HaQQ2BJWM: image5 ? ? props.HaQQ2BJWM ? ? {
            pixelHeight: 850,
            pixelWidth: 1144,
            src: "https://framerusercontent.com/images/MRNZnm8oX4TN995oGo4jWqPreA.png?width=1144&height=850",
            srcSet: "https://framerusercontent.com/images/MRNZnm8oX4TN995oGo4jWqPreA.png?scale-down-to=512&width=1144&height=850 512w,https://framerusercontent.com/images/MRNZnm8oX4TN995oGo4jWqPreA.png?scale-down-to=1024&width=1144&height=850 1024w,https://framerusercontent.com/images/MRNZnm8oX4TN995oGo4jWqPreA.png?width=1144&height=850 1144w"
        },
        IszbDCIOc: title5 ? ? props.IszbDCIOc ? ? "WEBSITE DESIGN",
        JhRen4I_0: title3 ? ? props.JhRen4I_0 ? ? "WEBSITE DESIGN",
        KX7KRKmIM: image2 ? ? props.KX7KRKmIM ? ? {
            pixelHeight: 850,
            pixelWidth: 1144,
            src: "https://framerusercontent.com/images/MRNZnm8oX4TN995oGo4jWqPreA.png?width=1144&height=850",
            srcSet: "https://framerusercontent.com/images/MRNZnm8oX4TN995oGo4jWqPreA.png?scale-down-to=512&width=1144&height=850 512w,https://framerusercontent.com/images/MRNZnm8oX4TN995oGo4jWqPreA.png?scale-down-to=1024&width=1144&height=850 1024w,https://framerusercontent.com/images/MRNZnm8oX4TN995oGo4jWqPreA.png?width=1144&height=850 1144w"
        },
        LHfLHr6TF: link1 ? ? props.LHfLHr6TF,
        mUzwET1Ix: cursor ? ? props.mUzwET1Ix,
        nN3KCdL8v: title1 ? ? props.nN3KCdL8v ? ? "WEBSITE DESIGN",
        nWdiJ6BDt: link3 ? ? props.nWdiJ6BDt,
        PUjhBs7tJ: image3 ? ? props.PUjhBs7tJ ? ? {
            pixelHeight: 850,
            pixelWidth: 1144,
            src: "https://framerusercontent.com/images/MRNZnm8oX4TN995oGo4jWqPreA.png?width=1144&height=850",
            srcSet: "https://framerusercontent.com/images/MRNZnm8oX4TN995oGo4jWqPreA.png?scale-down-to=512&width=1144&height=850 512w,https://framerusercontent.com/images/MRNZnm8oX4TN995oGo4jWqPreA.png?scale-down-to=1024&width=1144&height=850 1024w,https://framerusercontent.com/images/MRNZnm8oX4TN995oGo4jWqPreA.png?width=1144&height=850 1144w"
        },
        pX4YVkI63: title2 ? ? props.pX4YVkI63 ? ? "WEBSITE DESIGN",
        SeAgW_Svg: image6 ? ? props.SeAgW_Svg ? ? {
            pixelHeight: 850,
            pixelWidth: 1144,
            src: "https://framerusercontent.com/images/MRNZnm8oX4TN995oGo4jWqPreA.png?width=1144&height=850",
            srcSet: "https://framerusercontent.com/images/MRNZnm8oX4TN995oGo4jWqPreA.png?scale-down-to=512&width=1144&height=850 512w,https://framerusercontent.com/images/MRNZnm8oX4TN995oGo4jWqPreA.png?scale-down-to=1024&width=1144&height=850 1024w,https://framerusercontent.com/images/MRNZnm8oX4TN995oGo4jWqPreA.png?width=1144&height=850 1144w"
        },
        UHHeeF5QI: image4 ? ? props.UHHeeF5QI ? ? {
            pixelHeight: 850,
            pixelWidth: 1144,
            src: "https://framerusercontent.com/images/MRNZnm8oX4TN995oGo4jWqPreA.png?width=1144&height=850",
            srcSet: "https://framerusercontent.com/images/MRNZnm8oX4TN995oGo4jWqPreA.png?scale-down-to=512&width=1144&height=850 512w,https://framerusercontent.com/images/MRNZnm8oX4TN995oGo4jWqPreA.png?scale-down-to=1024&width=1144&height=850 1024w,https://framerusercontent.com/images/MRNZnm8oX4TN995oGo4jWqPreA.png?width=1144&height=850 1144w"
        },
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "h3UYmb6_l",
        yHfqSNGHO: title6 ? ? props.yHfqSNGHO ? ? "WEBSITE DESIGN",
        ZAVV92XrN: link5 ? ? props.ZAVV92XrN
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        mUzwET1Ix,
        e6r1XTL03,
        "nN3KCdL8v": externalnN3KCdL8v,
        "onnN3KCdL8vChange": setExternalnN3KCdL8v,
        LHfLHr6TF,
        KX7KRKmIM,
        "pX4YVkI63": externalpX4YVkI63,
        "onpX4YVkI63Change": setExternalpX4YVkI63,
        fiyb2IThv,
        PUjhBs7tJ,
        "JhRen4I_0": externalJhRen4I_0,
        "onJhRen4I_0Change": setExternalJhRen4I_0,
        nWdiJ6BDt,
        UHHeeF5QI,
        "fhhHabEMA": externalfhhHabEMA,
        "onfhhHabEMAChange": setExternalfhhHabEMA,
        f_jVoJ8Dh,
        HaQQ2BJWM,
        "IszbDCIOc": externalIszbDCIOc,
        "onIszbDCIOcChange": setExternalIszbDCIOc,
        ZAVV92XrN,
        SeAgW_Svg,
        "yHfqSNGHO": externalyHfqSNGHO,
        "onyHfqSNGHOChange": setExternalyHfqSNGHO,
        GMhjAY4Gg,
        ...restProps
    } = getProps(props);
    const [nN3KCdL8v, setnN3KCdL8v] = useStateVariable(externalnN3KCdL8v, setExternalnN3KCdL8v);
    const [pX4YVkI63, setpX4YVkI63] = useStateVariable(externalpX4YVkI63, setExternalpX4YVkI63);
    const [JhRen4I_0, setJhRen4I_0] = useStateVariable(externalJhRen4I_0, setExternalJhRen4I_0);
    const [fhhHabEMA, setfhhHabEMA] = useStateVariable(externalfhhHabEMA, setExternalfhhHabEMA);
    const [IszbDCIOc, setIszbDCIOc] = useStateVariable(externalIszbDCIOc, setExternalIszbDCIOc);
    const [yHfqSNGHO, setyHfqSNGHO] = useStateVariable(externalyHfqSNGHO, setExternalyHfqSNGHO);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "h3UYmb6_l",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const {
        activeVariantCallback,
        delay
    } = useActiveVariantCallback(baseVariant);
    const gwAGbD8B01agvv2w = activeVariantCallback(async (...args) => {
        setVariant("h3UYmb6_l");
    });
    const gwAGbD8B0bnvs2r = activeVariantCallback(async (...args) => {
        setVariant("SKuxYYyD6");
    });
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    const isDisplayed = () => {
        if (baseVariant === "SKuxYYyD6") return false;
        return true;
    };
    const isDisplayed1 = () => {
        if (baseVariant === "SKuxYYyD6") return true;
        return false;
    };
    const isDisplayed2 = () => {
        if (baseVariant === "uDo_SmVsc") return false;
        return true;
    };
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsxs(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-1nuaa0m", className, classNames),
                    "data-framer-name": "Column",
                    layoutDependency: layoutDependency,
                    layoutId: "h3UYmb6_l",
                    ref: refBinding,
                    style: { ...style
                    },
                    ...addPropertyOverrides({
                        SKuxYYyD6: {
                            "data-framer-name": "List"
                        },
                        uDo_SmVsc: {
                            "data-framer-name": "Phone"
                        }
                    }, baseVariant, gestureVariant),
                    children: [isDisplayed() && /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                        height: 483,
                        width: componentViewport ? .width || "100vw",
                        y: (componentViewport ? .y || 0) + 0 + (((componentViewport ? .height || 483) - 0 - 483) / 2 + 0 + 0),
                        ...addPropertyOverrides({
                            uDo_SmVsc: {
                                y: (componentViewport ? .y || 0) + 0 + (((componentViewport ? .height || 2237) - 0 - 483) / 2 + 0 + 0)
                            }
                        }, baseVariant, gestureVariant),
                        children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                            className: "framer-odp4y9-container",
                            layoutDependency: layoutDependency,
                            layoutId: "dRYNxbGYB-container",
                            nodeId: "dRYNxbGYB",
                            rendersWithMotion: true,
                            scopeId: "BWMv0YBCJ",
                            children: /*#__PURE__*/ _jsx(WorkColumnWithVariantAppearEffect, {
                                __framer__animateOnce: false,
                                __framer__targets: [{
                                    ref: QACZQTXxi,
                                    target: "SgnQ0C3Wx"
                                }, {
                                    ref: HjzPlJrPN,
                                    target: "IsSXdWv2d"
                                }, {
                                    ref: IuDRA_bKL,
                                    target: "PPxM05Qjb"
                                }, {
                                    ref: E0RL6e4ta,
                                    target: "RfoN2TlKW"
                                }, {
                                    ref: X_RoM5kx7,
                                    target: "malNPFB2D"
                                }, {
                                    ref: sT8NgyIwH,
                                    target: "VU3dYWesn"
                                }],
                                __framer__threshold: 1,
                                __framer__variantAppearEffectEnabled: true,
                                ALX5DKeMl: toResponsiveImage(e6r1XTL03),
                                c4aqhBTgq: LHfLHr6TF,
                                cj9P7ONpM: f_jVoJ8Dh,
                                CjvG6aWk_: toResponsiveImage(PUjhBs7tJ),
                                DOYJfBBE3: yHfqSNGHO,
                                EgZWTIaq9: nN3KCdL8v,
                                height: "100%",
                                id: "dRYNxbGYB",
                                layoutId: "dRYNxbGYB",
                                MrBrJfLkE: toResponsiveImage(KX7KRKmIM),
                                onDOYJfBBE3Change: setyHfqSNGHO,
                                onEgZWTIaq9Change: setnN3KCdL8v,
                                onqjZ6AGDErChange: setJhRen4I_0,
                                onTFmiJGLYPChange: setfhhHabEMA,
                                onWIMWr9COCChange: setpX4YVkI63,
                                onXH7_6OftNChange: setIszbDCIOc,
                                qcNqdzcd1: GMhjAY4Gg,
                                qFagBS4wQ: mUzwET1Ix,
                                qjZ6AGDEr: JhRen4I_0,
                                style: {
                                    width: "100%"
                                },
                                tBabQp3BT: ZAVV92XrN,
                                TFmiJGLYP: fhhHabEMA,
                                variant: matchVariant("SgnQ0C3Wx"),
                                VhYSlMM_Q: nWdiJ6BDt,
                                width: "100%",
                                WIMWr9COC: pX4YVkI63,
                                XH7_6OftN: IszbDCIOc,
                                xjEdXR1MR: toResponsiveImage(UHHeeF5QI),
                                xpqo68wYR: fiyb2IThv,
                                YHPKbvuus: toResponsiveImage(SeAgW_Svg),
                                ZW6CwKNNc: toResponsiveImage(HaQQ2BJWM),
                                ...addPropertyOverrides({
                                    uDo_SmVsc: {
                                        qFagBS4wQ: undefined,
                                        variant: matchVariant("KeJ6ftBw6")
                                    }
                                }, baseVariant, gestureVariant)
                            })
                        })
                    }), isDisplayed1() && /*#__PURE__*/ _jsx(ComponentViewportProvider, { ...addPropertyOverrides({
                            SKuxYYyD6: {
                                height: 781,
                                width: componentViewport ? .width || "100vw",
                                y: (componentViewport ? .y || 0) + 0 + (((componentViewport ? .height || 781) - 0 - 781) / 2 + 0 + 0)
                            }
                        }, baseVariant, gestureVariant),
                        children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                            className: "framer-6r7xl3-container",
                            layoutDependency: layoutDependency,
                            layoutId: "WaQKqu2nR-container",
                            nodeId: "WaQKqu2nR",
                            rendersWithMotion: true,
                            scopeId: "BWMv0YBCJ",
                            children: /*#__PURE__*/ _jsx(WorkList, {
                                BIelMZnmR: toResponsiveImage(HaQQ2BJWM),
                                D5ntm32my: yHfqSNGHO,
                                dlBRhPVCY: toResponsiveImage(PUjhBs7tJ),
                                dquZ8ACJd: GMhjAY4Gg,
                                ERx8nTTUu: toResponsiveImage(UHHeeF5QI),
                                EtuOs7Ir7: pX4YVkI63,
                                GyybUT3Ht: JhRen4I_0,
                                Hc_Noyv11: LHfLHr6TF,
                                height: "100%",
                                id: "WaQKqu2nR",
                                j8yRQ1QJ7: nWdiJ6BDt,
                                layoutId: "WaQKqu2nR",
                                oHcEIeIgT: IszbDCIOc,
                                onD5ntm32myChange: setyHfqSNGHO,
                                onEtuOs7Ir7Change: setpX4YVkI63,
                                onGyybUT3HtChange: setJhRen4I_0,
                                onoHcEIeIgTChange: setIszbDCIOc,
                                onOtEWVOI4JChange: setfhhHabEMA,
                                onrUirTmq4pChange: setnN3KCdL8v,
                                OtEWVOI4J: fhhHabEMA,
                                pyRNRhbB7: toResponsiveImage(SeAgW_Svg),
                                rUirTmq4p: nN3KCdL8v,
                                rzxKgeyAO: f_jVoJ8Dh,
                                style: {
                                    width: "100%"
                                },
                                T0K0p6oh0: fiyb2IThv,
                                variant: matchVariant("keuUWJKJx"),
                                Vdl6iZFII: ZAVV92XrN,
                                width: "100%",
                                yPBMmunCD: mUzwET1Ix,
                                YwfRBi6gu: toResponsiveImage(KX7KRKmIM),
                                zA9JZEqrV: toResponsiveImage(e6r1XTL03)
                            })
                        })
                    }), isDisplayed2() && /*#__PURE__*/ _jsxs(MotionDivWithFX, {
                        __framer__animate: {
                            transition: transition2
                        },
                        __framer__animateOnce: true,
                        __framer__enter: animation,
                        __framer__exit: animation1,
                        __framer__styleAppearEffectEnabled: true,
                        __framer__threshold: .5,
                        __perspectiveFX: false,
                        __smartComponentFX: true,
                        __targetOpacity: 1,
                        className: "framer-1hvwk6l",
                        "data-framer-name": "switch",
                        layoutDependency: layoutDependency,
                        layoutId: "BiIrY5eax",
                        children: [ /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                            height: 22,
                            y: (componentViewport ? .y || 0) + 0 + 0,
                            children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                className: "framer-ahcitk-container",
                                layoutDependency: layoutDependency,
                                layoutId: "RYJHood1j-container",
                                nodeId: "RYJHood1j",
                                rendersWithMotion: true,
                                scopeId: "BWMv0YBCJ",
                                children: /*#__PURE__*/ _jsx(WorkSwitch, {
                                    height: "100%",
                                    id: "RYJHood1j",
                                    layoutId: "RYJHood1j",
                                    variant: matchVariant("XEFVnqTnB"),
                                    width: "100%",
                                    XIDnl9Oir: "[COLUMN]",
                                    ...addPropertyOverrides({
                                        SKuxYYyD6: {
                                            gwAGbD8B0: gwAGbD8B01agvv2w,
                                            variant: matchVariant("HT4NjZwrH")
                                        }
                                    }, baseVariant, gestureVariant)
                                })
                            })
                        }), /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                            height: 22,
                            y: (componentViewport ? .y || 0) + 0 + 0,
                            children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                className: "framer-1pzrbmt-container",
                                layoutDependency: layoutDependency,
                                layoutId: "J3AVKEYlr-container",
                                nodeId: "J3AVKEYlr",
                                rendersWithMotion: true,
                                scopeId: "BWMv0YBCJ",
                                children: /*#__PURE__*/ _jsx(WorkSwitch, {
                                    gwAGbD8B0: gwAGbD8B0bnvs2r,
                                    height: "100%",
                                    id: "J3AVKEYlr",
                                    layoutId: "J3AVKEYlr",
                                    variant: matchVariant("HT4NjZwrH"),
                                    width: "100%",
                                    XIDnl9Oir: "[LIST]",
                                    ...addPropertyOverrides({
                                        SKuxYYyD6: {
                                            gwAGbD8B0: undefined,
                                            variant: matchVariant("XEFVnqTnB")
                                        }
                                    }, baseVariant, gestureVariant)
                                })
                            })
                        })]
                    })]
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-xZCBi.framer-hcp00x, .framer-xZCBi .framer-hcp00x { display: block; }", ".framer-xZCBi.framer-1nuaa0m { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1072px; }", ".framer-xZCBi .framer-odp4y9-container, .framer-xZCBi .framer-6r7xl3-container { flex: none; height: auto; position: relative; width: 100%; }", ".framer-xZCBi .framer-1hvwk6l { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; left: 0px; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: absolute; top: 0px; width: min-content; z-index: 1; }", ".framer-xZCBi .framer-ahcitk-container, .framer-xZCBi .framer-1pzrbmt-container { flex: none; height: auto; position: relative; width: auto; }", ".framer-xZCBi.framer-v-19er1hx.framer-1nuaa0m { width: 390px; }"];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 483
 * @framerIntrinsicWidth 1072
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"SKuxYYyD6":{"layout":["fixed","auto"]},"uDo_SmVsc":{"layout":["fixed","auto"]}}}
 * @framerVariables {"mUzwET1Ix":"cursor","e6r1XTL03":"image1","nN3KCdL8v":"title1","LHfLHr6TF":"link1","KX7KRKmIM":"image2","pX4YVkI63":"title2","fiyb2IThv":"link2","PUjhBs7tJ":"image3","JhRen4I_0":"title3","nWdiJ6BDt":"link3","UHHeeF5QI":"image4","fhhHabEMA":"title4","f_jVoJ8Dh":"link4","HaQQ2BJWM":"image5","IszbDCIOc":"title5","ZAVV92XrN":"link5","SeAgW_Svg":"image6","yHfqSNGHO":"title6","GMhjAY4Gg":"link6"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerBWMv0YBCJ = withCSS(Component, css, "framer-xZCBi");
export default FramerBWMv0YBCJ;
FramerBWMv0YBCJ.displayName = "work";
FramerBWMv0YBCJ.defaultProps = {
    height: 483,
    width: 1072
};
addPropertyControls(FramerBWMv0YBCJ, {
    variant: {
        options: ["h3UYmb6_l", "SKuxYYyD6", "uDo_SmVsc"],
        optionTitles: ["Column", "List", "Phone"],
        title: "Variant",
        type: ControlType.Enum
    },
    mUzwET1Ix: {
        title: "Cursor",
        type: ControlType.CustomCursor
    },
    e6r1XTL03: {
        __defaultAssetReference: "data:framer/asset-reference,MRNZnm8oX4TN995oGo4jWqPreA.png?originalFilename=Rectangle+6.png&width=1144&height=850",
        title: "Image 1",
        type: ControlType.ResponsiveImage
    },
    nN3KCdL8v: {
        defaultValue: "WEBSITE DESIGN",
        displayTextArea: false,
        title: "Title 1",
        type: ControlType.String
    },
    onnN3KCdL8vChange: {
        changes: "nN3KCdL8v",
        type: ControlType.ChangeHandler
    },
    LHfLHr6TF: {
        title: "Link 1",
        type: ControlType.Link
    },
    KX7KRKmIM: {
        __defaultAssetReference: "data:framer/asset-reference,MRNZnm8oX4TN995oGo4jWqPreA.png?originalFilename=Rectangle+6.png&width=1144&height=850",
        title: "Image 2",
        type: ControlType.ResponsiveImage
    },
    pX4YVkI63: {
        defaultValue: "WEBSITE DESIGN",
        displayTextArea: false,
        title: "Title 2",
        type: ControlType.String
    },
    onpX4YVkI63Change: {
        changes: "pX4YVkI63",
        type: ControlType.ChangeHandler
    },
    fiyb2IThv: {
        title: "Link 2",
        type: ControlType.Link
    },
    PUjhBs7tJ: {
        __defaultAssetReference: "data:framer/asset-reference,MRNZnm8oX4TN995oGo4jWqPreA.png?originalFilename=Rectangle+6.png&width=1144&height=850",
        title: "Image 3",
        type: ControlType.ResponsiveImage
    },
    JhRen4I_0: {
        defaultValue: "WEBSITE DESIGN",
        displayTextArea: false,
        title: "Title 3",
        type: ControlType.String
    },
    onJhRen4I_0Change: {
        changes: "JhRen4I_0",
        type: ControlType.ChangeHandler
    },
    nWdiJ6BDt: {
        title: "Link 3",
        type: ControlType.Link
    },
    UHHeeF5QI: {
        __defaultAssetReference: "data:framer/asset-reference,MRNZnm8oX4TN995oGo4jWqPreA.png?originalFilename=Rectangle+6.png&width=1144&height=850",
        title: "Image 4",
        type: ControlType.ResponsiveImage
    },
    fhhHabEMA: {
        defaultValue: "WEBSITE DESIGN",
        displayTextArea: false,
        title: "Title 4",
        type: ControlType.String
    },
    onfhhHabEMAChange: {
        changes: "fhhHabEMA",
        type: ControlType.ChangeHandler
    },
    f_jVoJ8Dh: {
        title: "Link 4",
        type: ControlType.Link
    },
    HaQQ2BJWM: {
        __defaultAssetReference: "data:framer/asset-reference,MRNZnm8oX4TN995oGo4jWqPreA.png?originalFilename=Rectangle+6.png&width=1144&height=850",
        title: "Image 5",
        type: ControlType.ResponsiveImage
    },
    IszbDCIOc: {
        defaultValue: "WEBSITE DESIGN",
        displayTextArea: false,
        title: "Title 5",
        type: ControlType.String
    },
    onIszbDCIOcChange: {
        changes: "IszbDCIOc",
        type: ControlType.ChangeHandler
    },
    ZAVV92XrN: {
        title: "Link 5",
        type: ControlType.Link
    },
    SeAgW_Svg: {
        __defaultAssetReference: "data:framer/asset-reference,MRNZnm8oX4TN995oGo4jWqPreA.png?originalFilename=Rectangle+6.png&width=1144&height=850",
        title: "Image 6",
        type: ControlType.ResponsiveImage
    },
    yHfqSNGHO: {
        defaultValue: "WEBSITE DESIGN",
        displayTextArea: false,
        title: "Title 6",
        type: ControlType.String
    },
    onyHfqSNGHOChange: {
        changes: "yHfqSNGHO",
        type: ControlType.ChangeHandler
    },
    GMhjAY4Gg: {
        title: "Link 6",
        type: ControlType.Link
    }
});
addFonts(FramerBWMv0YBCJ, [{
    explicitInter: true,
    fonts: []
}, ...WorkColumnFonts, ...WorkListFonts, ...WorkSwitchFonts], {
    supportsExplicitInterCodegen: true
});
FramerBWMv0YBCJ.loader = {
    load: (props, context) => {
        const locale = context.locale;
        return Promise.allSettled([forwardLoader(WorkColumn, {}, context), forwardLoader(WorkList, {}, context), forwardLoader(WorkSwitch, {}, context)]);
    }
};
export const __FramerMetadata__ = {
    "exports": {
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "reactComponent",
            "name": "FramerBWMv0YBCJ",
            "slots": [],
            "annotations": {
                "framerContractVersion": "1",
                "framerImmutableVariables": "true",
                "framerColorSyntax": "true",
                "framerIntrinsicWidth": "1072",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"auto\"]},\"SKuxYYyD6\":{\"layout\":[\"fixed\",\"auto\"]},\"uDo_SmVsc\":{\"layout\":[\"fixed\",\"auto\"]}}}",
                "framerIntrinsicHeight": "483",
                "framerComponentViewportWidth": "true",
                "framerDisplayContentsDiv": "false",
                "framerAutoSizeImages": "true",
                "framerVariables": "{\"mUzwET1Ix\":\"cursor\",\"e6r1XTL03\":\"image1\",\"nN3KCdL8v\":\"title1\",\"LHfLHr6TF\":\"link1\",\"KX7KRKmIM\":\"image2\",\"pX4YVkI63\":\"title2\",\"fiyb2IThv\":\"link2\",\"PUjhBs7tJ\":\"image3\",\"JhRen4I_0\":\"title3\",\"nWdiJ6BDt\":\"link3\",\"UHHeeF5QI\":\"image4\",\"fhhHabEMA\":\"title4\",\"f_jVoJ8Dh\":\"link4\",\"HaQQ2BJWM\":\"image5\",\"IszbDCIOc\":\"title5\",\"ZAVV92XrN\":\"link5\",\"SeAgW_Svg\":\"image6\",\"yHfqSNGHO\":\"title6\",\"GMhjAY4Gg\":\"link6\"}"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}