// Generated by Framer (bee8ea6)
export default function metadata(params, activeLocale) {
    return {
        description: "A CONSTANTLY EVOLVING BEING DRIVEN BY A PASSION FOR LIFELONG LEARNING AND THE DESIRE TO LEAVE A LASTING IMPACT.",
        favicon: "https://framerusercontent.com/assets/JT1jrsDofxbN9oIxUc5ijcNVlUM.png",
        robots: "max-image-preview:large",
        socialImage: "https://framerusercontent.com/assets/jfL5IodM3mjaI62YX8aYpbHbQw.png",
        title: "Tanisq Pandey"
    };
}
export const metadataVersion = 1;
export const __FramerMetadata__ = {
    "exports": {
        "metadataVersion": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "function",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}