// Generated by Framer (f353506)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ComponentViewportProvider,
    ControlType,
    cx,
    forwardLoader,
    getFonts,
    RichText,
    SmartComponentScopedContainer,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import Line from "https://framerusercontent.com/modules/DEQJkEyUiITjxdpq7AiC/SeRZ2GoS5FuLi5jQtJev/uIEkdrDi2.js";
const LineFonts = getFonts(Line);
const cycleOrder = ["mtsfTkGyl", "vZVBSBh27"];
const serializationHash = "framer-O5Y4N";
const variantClassNames = {
    mtsfTkGyl: "framer-v-1ghkcc1",
    vZVBSBh27: "framer-v-wykzab"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const LALONpGOM = undefined;
const jxz9MLZGK = undefined;
const dPEVdtjj9 = undefined;
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const humanReadableVariantMap = {
    "Not Selected": "mtsfTkGyl",
    Selected: "vZVBSBh27"
};
const Variants = motion.create(React.Fragment);
const getProps = ({
    cursor,
    height,
    id,
    index,
    title,
    width,
    ...props
}) => {
    return { ...props,
        dPEVdtjj9: title ? ? props.dPEVdtjj9 ? ? "WEBSITE DESIGN",
        jxz9MLZGK: index ? ? props.jxz9MLZGK ? ? "001",
        LALONpGOM: cursor ? ? props.LALONpGOM,
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "mtsfTkGyl"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        jxz9MLZGK,
        dPEVdtjj9,
        LALONpGOM,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "mtsfTkGyl",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsxs(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-1ghkcc1", className, classNames),
                    "data-framer-cursor": LALONpGOM,
                    "data-framer-name": "Not Selected",
                    layoutDependency: layoutDependency,
                    layoutId: "mtsfTkGyl",
                    ref: refBinding,
                    style: { ...style
                    },
                    ...addPropertyOverrides({
                        vZVBSBh27: {
                            "data-framer-name": "Selected"
                        }
                    }, baseVariant, gestureVariant),
                    children: [ /*#__PURE__*/ _jsxs(motion.div, {
                        className: "framer-ae5x35",
                        "data-framer-name": "content",
                        layoutDependency: layoutDependency,
                        layoutId: "Nj01rqqcN",
                        children: [ /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.p, {
                                    dir: "auto",
                                    style: {
                                        "--font-selector": "R0Y7R2Vpc3QgTW9uby1yZWd1bGFy",
                                        "--framer-font-family": '"Geist Mono", monospace',
                                        "--framer-font-size": "14px",
                                        "--framer-letter-spacing": "0.03em",
                                        "--framer-line-height": "1em",
                                        "--framer-text-color": "var(--extracted-r6o4lv, var(--token-0476634d-d018-44af-ab6c-08b29120481d, rgb(158, 158, 158)))"
                                    },
                                    children: "001"
                                })
                            }),
                            className: "framer-13iumm0",
                            fonts: ["GF;Geist Mono-regular"],
                            layoutDependency: layoutDependency,
                            layoutId: "h0FlMZHef",
                            style: {
                                "--extracted-r6o4lv": "var(--token-0476634d-d018-44af-ab6c-08b29120481d, rgb(158, 158, 158))",
                                "--framer-link-text-color": "rgb(0, 153, 255)",
                                "--framer-link-text-decoration": "underline"
                            },
                            text: jxz9MLZGK,
                            variants: {
                                vZVBSBh27: {
                                    "--extracted-r6o4lv": "var(--token-6c52689b-2844-43ed-ba14-1d9e767fc7ae, rgb(36, 36, 36))"
                                }
                            },
                            verticalAlignment: "top",
                            withExternalLayout: true,
                            ...addPropertyOverrides({
                                vZVBSBh27: {
                                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                                        children: /*#__PURE__*/ _jsx(motion.p, {
                                            dir: "auto",
                                            style: {
                                                "--font-selector": "R0Y7R2Vpc3QgTW9uby1yZWd1bGFy",
                                                "--framer-font-family": '"Geist Mono", monospace',
                                                "--framer-font-size": "14px",
                                                "--framer-letter-spacing": "0.03em",
                                                "--framer-line-height": "1em",
                                                "--framer-text-color": "var(--extracted-r6o4lv, var(--token-6c52689b-2844-43ed-ba14-1d9e767fc7ae, rgb(36, 36, 36)))"
                                            },
                                            children: "001"
                                        })
                                    })
                                }
                            }, baseVariant, gestureVariant)
                        }), /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.p, {
                                    dir: "auto",
                                    style: {
                                        "--font-selector": "R0Y7R2Vpc3QtcmVndWxhcg==",
                                        "--framer-font-family": '"Geist", "Geist Placeholder", sans-serif',
                                        "--framer-font-size": "48px",
                                        "--framer-letter-spacing": "-0.02em",
                                        "--framer-line-height": "1em",
                                        "--framer-text-color": "var(--extracted-r6o4lv, var(--token-0476634d-d018-44af-ab6c-08b29120481d, rgb(158, 158, 158)))",
                                        "--framer-text-transform": "uppercase"
                                    },
                                    children: "WEBSITE DESIGN"
                                })
                            }),
                            className: "framer-irufuz",
                            fonts: ["GF;Geist-regular"],
                            layoutDependency: layoutDependency,
                            layoutId: "Bu6phPaLs",
                            style: {
                                "--extracted-r6o4lv": "var(--token-0476634d-d018-44af-ab6c-08b29120481d, rgb(158, 158, 158))",
                                "--framer-link-text-color": "rgb(0, 153, 255)",
                                "--framer-link-text-decoration": "underline"
                            },
                            text: dPEVdtjj9,
                            variants: {
                                vZVBSBh27: {
                                    "--extracted-r6o4lv": "var(--token-6c52689b-2844-43ed-ba14-1d9e767fc7ae, rgb(36, 36, 36))"
                                }
                            },
                            verticalAlignment: "top",
                            withExternalLayout: true,
                            ...addPropertyOverrides({
                                vZVBSBh27: {
                                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                                        children: /*#__PURE__*/ _jsx(motion.p, {
                                            dir: "auto",
                                            style: {
                                                "--font-selector": "R0Y7R2Vpc3QtcmVndWxhcg==",
                                                "--framer-font-family": '"Geist", "Geist Placeholder", sans-serif',
                                                "--framer-font-size": "48px",
                                                "--framer-letter-spacing": "-0.02em",
                                                "--framer-line-height": "1em",
                                                "--framer-text-color": "var(--extracted-r6o4lv, var(--token-6c52689b-2844-43ed-ba14-1d9e767fc7ae, rgb(36, 36, 36)))",
                                                "--framer-text-transform": "uppercase"
                                            },
                                            children: "WEBSITE DESIGN"
                                        })
                                    })
                                }
                            }, baseVariant, gestureVariant)
                        })]
                    }), /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                        height: 1,
                        width: componentViewport ? .width || "100vw",
                        y: (componentViewport ? .y || 0) + 12 + (((componentViewport ? .height || 73) - 12 - 61) / 2 + 48 + 12),
                        children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                            className: "framer-ieky9t-container",
                            layoutDependency: layoutDependency,
                            layoutId: "Lt06Cr4Nr-container",
                            nodeId: "Lt06Cr4Nr",
                            rendersWithMotion: true,
                            scopeId: "H8Ue9kcuZ",
                            children: /*#__PURE__*/ _jsx(Line, {
                                height: "100%",
                                id: "Lt06Cr4Nr",
                                layoutId: "Lt06Cr4Nr",
                                mK_Oy4r3R: "var(--token-0476634d-d018-44af-ab6c-08b29120481d, rgb(158, 158, 158))",
                                style: {
                                    height: "100%",
                                    width: "100%"
                                },
                                width: "100%",
                                ...addPropertyOverrides({
                                    vZVBSBh27: {
                                        mK_Oy4r3R: "var(--token-6c52689b-2844-43ed-ba14-1d9e767fc7ae, rgb(36, 36, 36))"
                                    }
                                }, baseVariant, gestureVariant)
                            })
                        })
                    })]
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-O5Y4N.framer-az34kf, .framer-O5Y4N .framer-az34kf { display: block; }", ".framer-O5Y4N.framer-1ghkcc1 { align-content: flex-start; align-items: flex-start; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 12px 0px 0px 0px; position: relative; width: min-content; }", ".framer-O5Y4N .framer-ae5x35 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px 16px 0px 0px; position: relative; width: min-content; }", ".framer-O5Y4N .framer-13iumm0, .framer-O5Y4N .framer-irufuz { flex: none; height: auto; position: relative; white-space: pre; width: auto; }", ".framer-O5Y4N .framer-ieky9t-container { align-self: stretch; flex: none; height: 1px; position: relative; width: auto; }"];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 73
 * @framerIntrinsicWidth 446
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"vZVBSBh27":{"layout":["auto","auto"]}}}
 * @framerVariables {"jxz9MLZGK":"index","dPEVdtjj9":"title","LALONpGOM":"cursor"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerH8Ue9kcuZ = withCSS(Component, css, "framer-O5Y4N");
export default FramerH8Ue9kcuZ;
FramerH8Ue9kcuZ.displayName = "work-list-element";
FramerH8Ue9kcuZ.defaultProps = {
    height: 73,
    width: 446
};
addPropertyControls(FramerH8Ue9kcuZ, {
    variant: {
        options: ["mtsfTkGyl", "vZVBSBh27"],
        optionTitles: ["Not Selected", "Selected"],
        title: "Variant",
        type: ControlType.Enum
    },
    jxz9MLZGK: {
        defaultValue: "001",
        displayTextArea: false,
        title: "Index",
        type: ControlType.String
    },
    onjxz9MLZGKChange: {
        changes: "jxz9MLZGK",
        type: ControlType.ChangeHandler
    },
    dPEVdtjj9: {
        defaultValue: "WEBSITE DESIGN",
        displayTextArea: false,
        title: "Title",
        type: ControlType.String
    },
    ondPEVdtjj9Change: {
        changes: "dPEVdtjj9",
        type: ControlType.ChangeHandler
    },
    LALONpGOM: {
        title: "Cursor",
        type: ControlType.CustomCursor
    }
});
addFonts(FramerH8Ue9kcuZ, [{
    explicitInter: true,
    fonts: [{
        cssFamilyName: "Geist Mono",
        source: "google",
        style: "normal",
        uiFamilyName: "Geist Mono",
        url: "https://fonts.gstatic.com/s/geistmono/v4/or3yQ6H-1_WfwkMZI_qYPLs1a-t7PU0AbeE9KJ5W7ihaO_CS.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Geist",
        source: "google",
        style: "normal",
        uiFamilyName: "Geist",
        url: "https://fonts.gstatic.com/s/geist/v4/gyBhhwUxId8gMGYQMKR3pzfaWI_RnOM4mJPby1QNtA.woff2",
        weight: "400"
    }]
}, ...LineFonts], {
    supportsExplicitInterCodegen: true
});
FramerH8Ue9kcuZ.loader = {
    load: (props, context) => {
        const locale = context.locale;
        return Promise.allSettled([forwardLoader(Line, {}, context)]);
    }
};
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "FramerH8Ue9kcuZ",
            "slots": [],
            "annotations": {
                "framerDisplayContentsDiv": "false",
                "framerVariables": "{\"jxz9MLZGK\":\"index\",\"dPEVdtjj9\":\"title\",\"LALONpGOM\":\"cursor\"}",
                "framerColorSyntax": "true",
                "framerImmutableVariables": "true",
                "framerAutoSizeImages": "true",
                "framerIntrinsicHeight": "73",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"auto\",\"auto\"]},\"vZVBSBh27\":{\"layout\":[\"auto\",\"auto\"]}}}",
                "framerIntrinsicWidth": "446",
                "framerContractVersion": "1",
                "framerComponentViewportWidth": "true"
            }
        },
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./H8Ue9kcuZ.map