// Generated by Framer (edbb85b)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    getFonts,
    getFontsFromSharedStyle,
    Link,
    RichText,
    useActiveVariantCallback,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import ArrowUpRight from "https://framerusercontent.com/modules/f8Q5x3tcvy2sgigvrEse/WjPolkbUODUXgM3l5QnQ/X5rbDZv9v.js";
import * as sharedStyle from "https://framerusercontent.com/modules/7gvdWhLR8A11SwZKzoKr/5LdUszbKewmVBMh8BQZw/zS4IKGcPG.js";
const ArrowUpRightFonts = getFonts(ArrowUpRight);
const cycleOrder = ["LM6auV9nJ", "KSOjIbE7_"];
const serializationHash = "framer-F3IVt";
const variantClassNames = {
    KSOjIbE7_: "framer-v-1d9xsdf",
    LM6auV9nJ: "framer-v-1mp1zor"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const DMiikqTgh = undefined;
const WEMcCXbQA = undefined;
const RuND1NjLY = undefined;
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const humanReadableVariantMap = {
    Arrow: "KSOjIbE7_",
    Default: "LM6auV9nJ"
};
const Variants = motion.create(React.Fragment);
const getProps = ({
    click,
    content,
    height,
    id,
    link,
    width,
    ...props
}) => {
    return { ...props,
        DMiikqTgh: click ? ? props.DMiikqTgh,
        RuND1NjLY: content ? ? props.RuND1NjLY ? ? "WORK",
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "LM6auV9nJ",
        WEMcCXbQA: link ? ? props.WEMcCXbQA
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        RuND1NjLY,
        WEMcCXbQA,
        DMiikqTgh,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "LM6auV9nJ",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const {
        activeVariantCallback,
        delay
    } = useActiveVariantCallback(baseVariant);
    const onTapihbfku = activeVariantCallback(async (...args) => {
        setGestureState({
            isPressed: false
        });
        if (DMiikqTgh) {
            const res = await DMiikqTgh(...args);
            if (res === false) return false;
        }
    });
    const sharedStyleClassNames = [sharedStyle.className];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    const isDisplayed = () => {
        if (baseVariant === "KSOjIbE7_") return true;
        return false;
    };
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsx(Link, {
                    href: WEMcCXbQA,
                    motionChild: true,
                    nodeId: "LM6auV9nJ",
                    openInNewTab: false,
                    scopeId: "xeDvGrAWP",
                    smoothScroll: true,
                    children: /*#__PURE__*/ _jsxs(motion.a, { ...restProps,
                        ...gestureHandlers,
                        className: `${cx(scopingClassNames,"framer-1mp1zor",className,classNames)} framer-mxf0qx`,
                        "data-framer-name": "Default",
                        "data-highlight": true,
                        layoutDependency: layoutDependency,
                        layoutId: "LM6auV9nJ",
                        onTap: onTapihbfku,
                        ref: refBinding,
                        style: { ...style
                        },
                        ...addPropertyOverrides({
                            KSOjIbE7_: {
                                "data-framer-name": "Arrow"
                            }
                        }, baseVariant, gestureVariant),
                        children: [ /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.p, {
                                    className: "framer-styles-preset-n799mn",
                                    "data-styles-preset": "zS4IKGcPG",
                                    dir: "auto",
                                    children: "WORK"
                                })
                            }),
                            className: "framer-1xmbz5",
                            fonts: ["Inter"],
                            layoutDependency: layoutDependency,
                            layoutId: "s5kAaYFWd",
                            style: {
                                "--framer-link-text-color": "rgb(0, 153, 255)",
                                "--framer-link-text-decoration": "underline"
                            },
                            text: RuND1NjLY,
                            verticalAlignment: "top",
                            withExternalLayout: true
                        }), isDisplayed() && /*#__PURE__*/ _jsx(ArrowUpRight, {
                            animated: true,
                            className: "framer-hna1an",
                            layoutDependency: layoutDependency,
                            layoutId: "NadoAyRpl",
                            style: {
                                "--43q7um": "var(--token-c0b999b5-d23b-438e-9fb0-60835a3f22f2, rgb(224, 224, 224))"
                            }
                        })]
                    })
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-F3IVt.framer-mxf0qx, .framer-F3IVt .framer-mxf0qx { display: block; }", ".framer-F3IVt.framer-1mp1zor { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: flex-start; overflow: visible; padding: 8px 8px 8px 0px; position: relative; text-decoration: none; width: min-content; }", ".framer-F3IVt .framer-1xmbz5 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }", ".framer-F3IVt .framer-hna1an { flex: none; height: var(--framer-aspect-ratio-supported, 32px); position: relative; width: 32px; }", ".framer-F3IVt.framer-v-1d9xsdf.framer-1mp1zor { width: 184px; }", ".framer-F3IVt.framer-v-1d9xsdf .framer-1xmbz5 { flex: 1 0 0px; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }", ...sharedStyle.css];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 42
 * @framerIntrinsicWidth 89
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"KSOjIbE7_":{"layout":["fixed","auto"]}}}
 * @framerVariables {"RuND1NjLY":"content","WEMcCXbQA":"link","DMiikqTgh":"click"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerxeDvGrAWP = withCSS(Component, css, "framer-F3IVt");
export default FramerxeDvGrAWP;
FramerxeDvGrAWP.displayName = "nav-link-mobile";
FramerxeDvGrAWP.defaultProps = {
    height: 42,
    width: 89
};
addPropertyControls(FramerxeDvGrAWP, {
    variant: {
        options: ["LM6auV9nJ", "KSOjIbE7_"],
        optionTitles: ["Default", "Arrow"],
        title: "Variant",
        type: ControlType.Enum
    },
    RuND1NjLY: {
        defaultValue: "WORK",
        displayTextArea: false,
        title: "Content",
        type: ControlType.String
    },
    onRuND1NjLYChange: {
        changes: "RuND1NjLY",
        type: ControlType.ChangeHandler
    },
    WEMcCXbQA: {
        title: "Link",
        type: ControlType.Link
    },
    DMiikqTgh: {
        title: "Click",
        type: ControlType.EventHandler
    }
});
addFonts(FramerxeDvGrAWP, [{
    explicitInter: true,
    fonts: [{
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
        url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
        url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+1F00-1FFF",
        url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0370-03FF",
        url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
        url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
        url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
        weight: "400"
    }]
}, ...ArrowUpRightFonts, ...getFontsFromSharedStyle(sharedStyle.fonts)], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "FramerxeDvGrAWP",
            "slots": [],
            "annotations": {
                "framerDisplayContentsDiv": "false",
                "framerContractVersion": "1",
                "framerAutoSizeImages": "true",
                "framerImmutableVariables": "true",
                "framerColorSyntax": "true",
                "framerComponentViewportWidth": "true",
                "framerVariables": "{\"RuND1NjLY\":\"content\",\"WEMcCXbQA\":\"link\",\"DMiikqTgh\":\"click\"}",
                "framerIntrinsicWidth": "89",
                "framerIntrinsicHeight": "42",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"auto\",\"auto\"]},\"KSOjIbE7_\":{\"layout\":[\"fixed\",\"auto\"]}}}"
            }
        },
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}