// Generated by Framer (3f060d6)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ComponentViewportProvider,
    ControlType,
    cx,
    forwardLoader,
    getFonts,
    SmartComponentScopedContainer,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCodeBoundaryForOverrides,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import ArrowUpRight from "https://framerusercontent.com/modules/f8Q5x3tcvy2sgigvrEse/WjPolkbUODUXgM3l5QnQ/X5rbDZv9v.js";
import {
    withHoverSound
} from "https://framerusercontent.com/modules/Z1xf6IwyhFtCiejOpugF/2ADn5EleOMolnWCzYYw8/HoverSound.js";
import TextScramble from "https://framerusercontent.com/modules/hwyXKSBSUSfWE0hql0LO/rpUilysupUU2hlE2BlLC/TextScramble.js";
import Line from "https://framerusercontent.com/modules/DEQJkEyUiITjxdpq7AiC/SeRZ2GoS5FuLi5jQtJev/uIEkdrDi2.js";
const TextScrambleFonts = getFonts(TextScramble);
const LineFonts = getFonts(Line);
const ArrowUpRightFonts = getFonts(ArrowUpRight);
const MotionButtonWithHoverSoundyjzp7e = withCodeBoundaryForOverrides(motion.button, {
    nodeId: "JOLMHdS0x",
    override: withHoverSound,
    scopeId: "IlkJxQJRE"
});
const enabledGestures = {
    JOLMHdS0x: {
        hover: true
    }
};
const cycleOrder = ["JOLMHdS0x", "J1XZcVwL4", "FMaWDurog", "v48IvBYpW"];
const serializationHash = "framer-rfmyq";
const variantClassNames = {
    FMaWDurog: "framer-v-17s1an8",
    J1XZcVwL4: "framer-v-1xm7li0",
    JOLMHdS0x: "framer-v-yjzp7e",
    v48IvBYpW: "framer-v-1uqfe4u"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const S0mYPa1Ez = undefined;
const ncM9c2SOg = undefined;
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const humanReadableVariantMap = {
    Default: "JOLMHdS0x",
    Error: "v48IvBYpW",
    Loading: "FMaWDurog",
    Success: "J1XZcVwL4"
};
const Variants = motion.create(React.Fragment);
const getProps = ({
    color,
    content,
    height,
    id,
    width,
    ...props
}) => {
    return { ...props,
        ncM9c2SOg: color ? ? props.ncM9c2SOg ? ? "var(--token-6c52689b-2844-43ed-ba14-1d9e767fc7ae, rgb(36, 36, 36))",
        S0mYPa1Ez: content ? ? props.S0mYPa1Ez ? ? "START CONVERSATION",
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "JOLMHdS0x"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        ncM9c2SOg,
        S0mYPa1Ez,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "JOLMHdS0x",
        enabledGestures,
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    const isDisplayed = () => {
        if (["J1XZcVwL4", "FMaWDurog", "v48IvBYpW"].includes(baseVariant)) return false;
        return true;
    };
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsxs(MotionButtonWithHoverSoundyjzp7e, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-yjzp7e", className, classNames),
                    "data-framer-name": "Default",
                    "data-reset": "button",
                    layoutDependency: layoutDependency,
                    layoutId: "JOLMHdS0x",
                    ref: refBinding,
                    style: { ...style
                    },
                    ...addPropertyOverrides({
                        "JOLMHdS0x-hover": {
                            "data-framer-name": undefined
                        },
                        FMaWDurog: {
                            "data-framer-name": "Loading"
                        },
                        J1XZcVwL4: {
                            "data-framer-name": "Success"
                        },
                        v48IvBYpW: {
                            "data-framer-name": "Error"
                        }
                    }, baseVariant, gestureVariant),
                    children: [ /*#__PURE__*/ _jsxs(motion.div, {
                        className: "framer-i4mwhy",
                        "data-framer-name": "text",
                        layoutDependency: layoutDependency,
                        layoutId: "fMMqcdTFo",
                        children: [ /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                            children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                className: "framer-1h72kra-container",
                                "data-code-component-plugin-id": "84d4c1",
                                isAuthoredByUser: true,
                                layoutDependency: layoutDependency,
                                layoutId: "vrVHRT9er-container",
                                nodeId: "vrVHRT9er",
                                rendersWithMotion: true,
                                scopeId: "IlkJxQJRE",
                                children: /*#__PURE__*/ _jsx(TextScramble, {
                                    appearDelay: 100,
                                    characters: "!@#$%^&*()_+-=[]{}|;:,.<>?",
                                    duration: 800,
                                    font: {
                                        fontFamily: '"Geist", "Geist Placeholder", sans-serif',
                                        fontSize: "32px",
                                        fontStyle: "normal",
                                        fontWeight: 500,
                                        letterSpacing: "-0.02em",
                                        lineHeight: "1.3em"
                                    },
                                    height: "100%",
                                    id: "vrVHRT9er",
                                    layoutId: "vrVHRT9er",
                                    scrambleIntensity: 80,
                                    text: S0mYPa1Ez,
                                    textColor: ncM9c2SOg,
                                    triggerMode: "hover",
                                    width: "100%",
                                    ...addPropertyOverrides({
                                        FMaWDurog: {
                                            text: "WAIT",
                                            triggerMode: "appear"
                                        },
                                        J1XZcVwL4: {
                                            text: "THANKYOU",
                                            triggerMode: "appear"
                                        },
                                        v48IvBYpW: {
                                            text: "ERROR",
                                            triggerMode: "appear"
                                        }
                                    }, baseVariant, gestureVariant)
                                })
                            })
                        }), /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                            height: 1,
                            y: (componentViewport ? .y || 0) + (0 + ((componentViewport ? .height || 42.5) - 0 - 201) / 2) + 0 + 200,
                            children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                className: "framer-1y6rqfp-container",
                                layoutDependency: layoutDependency,
                                layoutId: "Ig2tV63Ka-container",
                                nodeId: "Ig2tV63Ka",
                                rendersWithMotion: true,
                                scopeId: "IlkJxQJRE",
                                children: /*#__PURE__*/ _jsx(Line, {
                                    height: "100%",
                                    id: "Ig2tV63Ka",
                                    layoutId: "Ig2tV63Ka",
                                    mK_Oy4r3R: ncM9c2SOg,
                                    style: {
                                        height: "100%",
                                        width: "100%"
                                    },
                                    width: "100%"
                                })
                            })
                        })]
                    }), isDisplayed() && /*#__PURE__*/ _jsx(ArrowUpRight, {
                        animated: true,
                        className: "framer-1rpwvwg",
                        layoutDependency: layoutDependency,
                        layoutId: "y3KV6Z20e",
                        style: {
                            "--43q7um": ncM9c2SOg,
                            rotate: 0
                        },
                        variants: {
                            "JOLMHdS0x-hover": {
                                rotate: 45
                            }
                        }
                    })]
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-rfmyq.framer-1sme68l, .framer-rfmyq .framer-1sme68l { display: block; }", ".framer-rfmyq.framer-yjzp7e { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: flex-start; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: min-content; }", ".framer-rfmyq .framer-i4mwhy { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }", ".framer-rfmyq .framer-1h72kra-container { flex: none; height: auto; position: relative; width: auto; }", ".framer-rfmyq .framer-1y6rqfp-container { align-self: stretch; flex: none; height: 1px; position: relative; width: auto; }", ".framer-rfmyq .framer-1rpwvwg { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 32px); position: relative; width: 32px; }", ".framer-rfmyq.framer-v-1xm7li0.framer-yjzp7e, .framer-rfmyq.framer-v-17s1an8.framer-yjzp7e, .framer-rfmyq.framer-v-1uqfe4u.framer-yjzp7e { cursor: unset; }"];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 42.5
 * @framerIntrinsicWidth 377
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"J1XZcVwL4":{"layout":["auto","auto"]},"FMaWDurog":{"layout":["auto","auto"]},"v48IvBYpW":{"layout":["auto","auto"]},"RR5jJamOX":{"layout":["auto","auto"]}}}
 * @framerVariables {"ncM9c2SOg":"color","S0mYPa1Ez":"content"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerIlkJxQJRE = withCSS(Component, css, "framer-rfmyq");
export default FramerIlkJxQJRE;
FramerIlkJxQJRE.displayName = "button-submit";
FramerIlkJxQJRE.defaultProps = {
    height: 42.5,
    width: 377
};
addPropertyControls(FramerIlkJxQJRE, {
    variant: {
        options: ["JOLMHdS0x", "J1XZcVwL4", "FMaWDurog", "v48IvBYpW"],
        optionTitles: ["Default", "Success", "Loading", "Error"],
        title: "Variant",
        type: ControlType.Enum
    },
    ncM9c2SOg: {
        defaultValue: 'var(--token-6c52689b-2844-43ed-ba14-1d9e767fc7ae, rgb(36, 36, 36)) /* {"name":"Dark"} */',
        title: "Color",
        type: ControlType.Color
    },
    S0mYPa1Ez: {
        defaultValue: "START CONVERSATION",
        title: "Content",
        type: ControlType.String
    },
    onS0mYPa1EzChange: {
        changes: "S0mYPa1Ez",
        type: ControlType.ChangeHandler
    }
});
addFonts(FramerIlkJxQJRE, [{
    explicitInter: true,
    fonts: [{
        cssFamilyName: "Geist",
        source: "google",
        style: "normal",
        uiFamilyName: "Geist",
        url: "https://fonts.gstatic.com/s/geist/v5/gyBhhwUxId8gMGYQMKR3pzfaWI_RruM4mJPby1QNtA.woff2",
        weight: "500"
    }]
}, ...TextScrambleFonts, ...LineFonts, ...ArrowUpRightFonts], {
    supportsExplicitInterCodegen: true
});
FramerIlkJxQJRE.loader = {
    load: (props, context) => {
        const locale = context.locale;
        return Promise.allSettled([forwardLoader(Line, {}, context)]);
    }
};
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "FramerIlkJxQJRE",
            "slots": [],
            "annotations": {
                "framerColorSyntax": "true",
                "framerAutoSizeImages": "true",
                "framerIntrinsicHeight": "42.5",
                "framerVariables": "{\"ncM9c2SOg\":\"color\",\"S0mYPa1Ez\":\"content\"}",
                "framerIntrinsicWidth": "377",
                "framerImmutableVariables": "true",
                "framerContractVersion": "1",
                "framerDisplayContentsDiv": "false",
                "framerComponentViewportWidth": "true",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"auto\",\"auto\"]},\"J1XZcVwL4\":{\"layout\":[\"auto\",\"auto\"]},\"FMaWDurog\":{\"layout\":[\"auto\",\"auto\"]},\"v48IvBYpW\":{\"layout\":[\"auto\",\"auto\"]},\"RR5jJamOX\":{\"layout\":[\"auto\",\"auto\"]}}}"
            }
        },
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}