// Generated by Framer (8442ab0)
import {
    jsx as _jsx
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    getFontsFromSharedStyle,
    RichText,
    useActiveVariantCallback,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import * as sharedStyle from "https://framerusercontent.com/modules/H6hD99Ser6a7jSGKTqaa/tdsPZQEcs8Zp0h8Mlppx/hbmnSL9G4.js";
const cycleOrder = ["XEFVnqTnB", "HT4NjZwrH"];
const serializationHash = "framer-0IhkS";
const variantClassNames = {
    HT4NjZwrH: "framer-v-tjgumx",
    XEFVnqTnB: "framer-v-1c9tiob"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const gwAGbD8B0 = undefined;
const XIDnl9Oir = undefined;
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const humanReadableVariantMap = {
    "Not Selected": "HT4NjZwrH",
    Selected: "XEFVnqTnB"
};
const Variants = motion.create(React.Fragment);
const getProps = ({
    click,
    height,
    id,
    text,
    width,
    ...props
}) => {
    return { ...props,
        gwAGbD8B0: click ? ? props.gwAGbD8B0,
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "XEFVnqTnB",
        XIDnl9Oir: text ? ? props.XIDnl9Oir ? ? "[COLUMN]"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        XIDnl9Oir,
        gwAGbD8B0,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "XEFVnqTnB",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const {
        activeVariantCallback,
        delay
    } = useActiveVariantCallback(baseVariant);
    const onTap1f9980d = activeVariantCallback(async (...args) => {
        setGestureState({
            isPressed: false
        });
        if (gwAGbD8B0) {
            const res = await gwAGbD8B0(...args);
            if (res === false) return false;
        }
    });
    const sharedStyleClassNames = [sharedStyle.className];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsx(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-1c9tiob", className, classNames),
                    "data-framer-name": "Selected",
                    "data-highlight": true,
                    layoutDependency: layoutDependency,
                    layoutId: "XEFVnqTnB",
                    onTap: onTap1f9980d,
                    ref: refBinding,
                    style: {
                        backgroundColor: "var(--token-6c52689b-2844-43ed-ba14-1d9e767fc7ae, rgb(36, 36, 36))",
                        ...style
                    },
                    variants: {
                        HT4NjZwrH: {
                            backgroundColor: "rgba(0, 0, 0, 0)"
                        }
                    },
                    ...addPropertyOverrides({
                        HT4NjZwrH: {
                            "data-framer-name": "Not Selected"
                        }
                    }, baseVariant, gestureVariant),
                    children: /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                                className: "framer-styles-preset-12e5cbe",
                                "data-styles-preset": "hbmnSL9G4",
                                dir: "auto",
                                style: {
                                    "--framer-text-color": "var(--extracted-r6o4lv, var(--token-be9ea0bc-8552-43c1-9925-5396d8470547, rgb(255, 255, 255)))"
                                },
                                children: "[COLUMN]"
                            })
                        }),
                        className: "framer-40ovx",
                        fonts: ["Inter"],
                        layoutDependency: layoutDependency,
                        layoutId: "sxC6QK44q",
                        style: {
                            "--extracted-r6o4lv": "var(--token-be9ea0bc-8552-43c1-9925-5396d8470547, rgb(255, 255, 255))",
                            "--framer-link-text-color": "rgb(0, 153, 255)",
                            "--framer-link-text-decoration": "underline"
                        },
                        text: XIDnl9Oir,
                        variants: {
                            HT4NjZwrH: {
                                "--extracted-r6o4lv": "var(--token-6c52689b-2844-43ed-ba14-1d9e767fc7ae, rgb(36, 36, 36))"
                            }
                        },
                        verticalAlignment: "top",
                        withExternalLayout: true,
                        ...addPropertyOverrides({
                            HT4NjZwrH: {
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                    children: /*#__PURE__*/ _jsx(motion.p, {
                                        className: "framer-styles-preset-12e5cbe",
                                        "data-styles-preset": "hbmnSL9G4",
                                        dir: "auto",
                                        style: {
                                            "--framer-text-color": "var(--extracted-r6o4lv, var(--token-6c52689b-2844-43ed-ba14-1d9e767fc7ae, rgb(36, 36, 36)))"
                                        },
                                        children: "[COLUMN]"
                                    })
                                })
                            }
                        }, baseVariant, gestureVariant)
                    })
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-0IhkS.framer-17f0uz8, .framer-0IhkS .framer-17f0uz8 { display: block; }", ".framer-0IhkS.framer-1c9tiob { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 4px 8px 4px 8px; position: relative; width: min-content; }", ".framer-0IhkS .framer-40ovx { flex: none; height: auto; position: relative; white-space: pre; width: auto; }", ...sharedStyle.css];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 22
 * @framerIntrinsicWidth 87
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"HT4NjZwrH":{"layout":["auto","auto"]}}}
 * @framerVariables {"XIDnl9Oir":"text","gwAGbD8B0":"click"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerI3FYJ2PFv = withCSS(Component, css, "framer-0IhkS");
export default FramerI3FYJ2PFv;
FramerI3FYJ2PFv.displayName = "work-switch";
FramerI3FYJ2PFv.defaultProps = {
    height: 22,
    width: 87
};
addPropertyControls(FramerI3FYJ2PFv, {
    variant: {
        options: ["XEFVnqTnB", "HT4NjZwrH"],
        optionTitles: ["Selected", "Not Selected"],
        title: "Variant",
        type: ControlType.Enum
    },
    XIDnl9Oir: {
        defaultValue: "[COLUMN]",
        title: "Text",
        type: ControlType.String
    },
    onXIDnl9OirChange: {
        changes: "XIDnl9Oir",
        type: ControlType.ChangeHandler
    },
    gwAGbD8B0: {
        title: "Click",
        type: ControlType.EventHandler
    }
});
addFonts(FramerI3FYJ2PFv, [{
    explicitInter: true,
    fonts: [{
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
        url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
        url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+1F00-1FFF",
        url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0370-03FF",
        url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
        url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
        weight: "400"
    }, {
        cssFamilyName: "Inter",
        source: "framer",
        style: "normal",
        uiFamilyName: "Inter",
        unicodeRange: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
        url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
        weight: "400"
    }]
}, ...getFontsFromSharedStyle(sharedStyle.fonts)], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "FramerI3FYJ2PFv",
            "slots": [],
            "annotations": {
                "framerAutoSizeImages": "true",
                "framerIntrinsicHeight": "22",
                "framerComponentViewportWidth": "true",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"auto\",\"auto\"]},\"HT4NjZwrH\":{\"layout\":[\"auto\",\"auto\"]}}}",
                "framerContractVersion": "1",
                "framerImmutableVariables": "true",
                "framerColorSyntax": "true",
                "framerIntrinsicWidth": "87",
                "framerDisplayContentsDiv": "false",
                "framerVariables": "{\"XIDnl9Oir\":\"text\",\"gwAGbD8B0\":\"click\"}"
            }
        },
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}