// Generated by Framer (02d7f84)
import {
    jsx as _jsx
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ComponentViewportProvider,
    ControlType,
    cx,
    getFonts,
    SmartComponentScopedContainer,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS,
    withFX
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import ScrollColorChangeText from "https://framerusercontent.com/modules/TMZFANgltC2aqg2iKUCu/6QUuBfK25JNX86Jyz9bW/ScrollColorChangeText.js";
const ScrollColorChangeTextFonts = getFonts(ScrollColorChangeText);
const MotionDivWithFX = withFX(motion.div);
const cycleOrder = ["F5Z5Wy32p", "qunrjHryV", "P9mJ0Yace"];
const serializationHash = "framer-LobWe";
const variantClassNames = {
    F5Z5Wy32p: "framer-v-1c0o53t",
    P9mJ0Yace: "framer-v-bad2iq",
    qunrjHryV: "framer-v-dxou1r"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const uRY_pb6U2 = undefined;
const FP7tUrPps = undefined;
const qaxcA7D5Q = undefined;
const F8We4KdSM = undefined;
const animation = {
    opacity: 0,
    rotate: 0,
    rotateX: 0,
    rotateY: 0,
    scale: 1,
    skewX: 0,
    skewY: 0,
    x: 0,
    y: 80
};
const transition1 = {
    bounce: 0,
    delay: 0,
    duration: 1.2,
    type: "spring"
};
const animation1 = {
    opacity: 0,
    rotate: 0,
    rotateX: 0,
    rotateY: 0,
    scale: 1,
    skewX: 0,
    skewY: 0,
    transition: transition1,
    x: 0,
    y: 80
};
const transition2 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const humanReadableVariantMap = {
    Desktop: "F5Z5Wy32p",
    Phone: "P9mJ0Yace",
    Tablet: "qunrjHryV"
};
const Variants = motion.create(React.Fragment);
const getProps = ({
    endColor,
    height,
    id,
    startColor,
    text,
    textBalance,
    width,
    ...props
}) => {
    return { ...props,
        F8We4KdSM: endColor ? ? props.F8We4KdSM ? ? "var(--token-6c52689b-2844-43ed-ba14-1d9e767fc7ae, rgb(36, 36, 36))",
        FP7tUrPps: textBalance ? ? props.FP7tUrPps,
        qaxcA7D5Q: startColor ? ? props.qaxcA7D5Q ? ? "var(--token-b5c8d8ec-0a9e-4754-a050-6407b6d1bb92, rgba(66, 66, 66, 0.5))",
        uRY_pb6U2: text ? ? props.uRY_pb6U2 ? ? "                         I DESIGN DIGITAL PRODUCTS THAT FEEL SIMPLE, USEFUL, AND HUMAN. I TURN COMPLEX PROBLEMS INTO CLEAR EXPERIENCES, WITH A LOT OF ATTENTION TO HOW PEOPLE ACTUALLY THINK, USE, AND EXPERIENCE PRODUCTS.\n",
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "F5Z5Wy32p"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        uRY_pb6U2,
        FP7tUrPps,
        qaxcA7D5Q,
        F8We4KdSM,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "F5Z5Wy32p",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition2,
                children: /*#__PURE__*/ _jsx(MotionDivWithFX, { ...restProps,
                    ...gestureHandlers,
                    __framer__animate: {
                        transition: transition1
                    },
                    __framer__animateOnce: true,
                    __framer__enter: animation,
                    __framer__exit: animation1,
                    __framer__styleAppearEffectEnabled: true,
                    __framer__threshold: .5,
                    __perspectiveFX: false,
                    __smartComponentFX: true,
                    __targetOpacity: 1,
                    className: cx(scopingClassNames, "framer-1c0o53t", className, classNames),
                    "data-framer-name": "Desktop",
                    layoutDependency: layoutDependency,
                    layoutId: "F5Z5Wy32p",
                    ref: refBinding,
                    style: { ...style
                    },
                    ...addPropertyOverrides({
                        P9mJ0Yace: {
                            "data-framer-name": "Phone"
                        },
                        qunrjHryV: {
                            "data-framer-name": "Tablet"
                        }
                    }, baseVariant, gestureVariant),
                    children: /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                        children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                            className: "framer-oxa5r6-container",
                            "data-code-component-plugin-id": "84d4c1",
                            isAuthoredByUser: true,
                            layoutDependency: layoutDependency,
                            layoutId: "S3DSbp60z-container",
                            nodeId: "S3DSbp60z",
                            rendersWithMotion: true,
                            scopeId: "yU8pOOSm0",
                            children: /*#__PURE__*/ _jsx(ScrollColorChangeText, {
                                endColor: F8We4KdSM,
                                font: {
                                    fontFamily: '"Geist", "Geist Placeholder", sans-serif',
                                    fontSize: "48px",
                                    fontStyle: "normal",
                                    fontWeight: 500,
                                    letterSpacing: "-0.02em",
                                    lineHeight: "1em"
                                },
                                height: "100%",
                                id: "S3DSbp60z",
                                layoutId: "S3DSbp60z",
                                startColor: qaxcA7D5Q,
                                style: {
                                    width: "100%"
                                },
                                text: uRY_pb6U2,
                                textBalance: FP7tUrPps,
                                width: "100%",
                                ...addPropertyOverrides({
                                    P9mJ0Yace: {
                                        font: {
                                            fontFamily: '"Geist", "Geist Placeholder", sans-serif',
                                            fontSize: "24px",
                                            fontStyle: "normal",
                                            fontWeight: 500,
                                            letterSpacing: "-0.02em",
                                            lineHeight: "1em"
                                        }
                                    },
                                    qunrjHryV: {
                                        font: {
                                            fontFamily: '"Geist", "Geist Placeholder", sans-serif',
                                            fontSize: "32px",
                                            fontStyle: "normal",
                                            fontWeight: 500,
                                            letterSpacing: "-0.02em",
                                            lineHeight: "1em"
                                        }
                                    }
                                }, baseVariant, gestureVariant)
                            })
                        })
                    })
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-LobWe.framer-xvmo3z, .framer-LobWe .framer-xvmo3z { display: block; }", ".framer-LobWe.framer-1c0o53t { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 1072px; }", ".framer-LobWe .framer-oxa5r6-container { flex: 1 0 0px; height: auto; position: relative; width: 1px; }"];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 240
 * @framerIntrinsicWidth 1072
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"qunrjHryV":{"layout":["fixed","auto"]},"P9mJ0Yace":{"layout":["fixed","auto"]}}}
 * @framerVariables {"uRY_pb6U2":"text","FP7tUrPps":"textBalance","qaxcA7D5Q":"startColor","F8We4KdSM":"endColor"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FrameryU8pOOSm0 = withCSS(Component, css, "framer-LobWe");
export default FrameryU8pOOSm0;
FrameryU8pOOSm0.displayName = "text-color-change";
FrameryU8pOOSm0.defaultProps = {
    height: 240,
    width: 1072
};
addPropertyControls(FrameryU8pOOSm0, {
    variant: {
        options: ["F5Z5Wy32p", "qunrjHryV", "P9mJ0Yace"],
        optionTitles: ["Desktop", "Tablet", "Phone"],
        title: "Variant",
        type: ControlType.Enum
    },
    uRY_pb6U2: {
        defaultValue: "                         I DESIGN DIGITAL PRODUCTS THAT FEEL SIMPLE, USEFUL, AND HUMAN. I TURN COMPLEX PROBLEMS INTO CLEAR EXPERIENCES, WITH A LOT OF ATTENTION TO HOW PEOPLE ACTUALLY THINK, USE, AND EXPERIENCE PRODUCTS.\n",
        displayTextArea: true,
        title: "Text",
        type: ControlType.String
    },
    onuRY_pb6U2Change: {
        changes: "uRY_pb6U2",
        type: ControlType.ChangeHandler
    },
    FP7tUrPps: {
        defaultValue: false,
        title: "Text Balance",
        type: ControlType.Boolean
    },
    onFP7tUrPpsChange: {
        changes: "FP7tUrPps",
        type: ControlType.ChangeHandler
    },
    qaxcA7D5Q: {
        defaultValue: 'var(--token-b5c8d8ec-0a9e-4754-a050-6407b6d1bb92, rgba(66, 66, 66, 0.5)) /* {"name":"Grey 50"} */',
        title: "Start Color",
        type: ControlType.Color
    },
    F8We4KdSM: {
        defaultValue: 'var(--token-6c52689b-2844-43ed-ba14-1d9e767fc7ae, rgb(36, 36, 36)) /* {"name":"Dark"} */',
        title: "End Color",
        type: ControlType.Color
    }
});
addFonts(FrameryU8pOOSm0, [{
    explicitInter: true,
    fonts: [{
        cssFamilyName: "Geist",
        source: "google",
        style: "normal",
        uiFamilyName: "Geist",
        url: "https://fonts.gstatic.com/s/geist/v4/gyBhhwUxId8gMGYQMKR3pzfaWI_RruM4mJPby1QNtA.woff2",
        weight: "500"
    }]
}, ...ScrollColorChangeTextFonts], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "reactComponent",
            "name": "FrameryU8pOOSm0",
            "slots": [],
            "annotations": {
                "framerAutoSizeImages": "true",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"auto\"]},\"qunrjHryV\":{\"layout\":[\"fixed\",\"auto\"]},\"P9mJ0Yace\":{\"layout\":[\"fixed\",\"auto\"]}}}",
                "framerDisplayContentsDiv": "false",
                "framerVariables": "{\"uRY_pb6U2\":\"text\",\"FP7tUrPps\":\"textBalance\",\"qaxcA7D5Q\":\"startColor\",\"F8We4KdSM\":\"endColor\"}",
                "framerContractVersion": "1",
                "framerImmutableVariables": "true",
                "framerComponentViewportWidth": "true",
                "framerColorSyntax": "true",
                "framerIntrinsicWidth": "1072",
                "framerIntrinsicHeight": "240"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./yU8pOOSm0.map