// Generated by Framer (3f060d6)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ComponentViewportProvider,
    ControlType,
    cx,
    getFonts,
    Instance,
    Link,
    SmartComponentScopedContainer,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCodeBoundaryForOverrides,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import Plus from "https://framerusercontent.com/modules/8lmJd8w75gKRoGT9q1K2/39RBLkdJurXVrrLMUbEn/feHWUubDx.js";
import ArrowUpRight from "https://framerusercontent.com/modules/f8Q5x3tcvy2sgigvrEse/WjPolkbUODUXgM3l5QnQ/X5rbDZv9v.js";
import {
    withHoverSound
} from "https://framerusercontent.com/modules/Z1xf6IwyhFtCiejOpugF/2ADn5EleOMolnWCzYYw8/HoverSound.js";
import TextScramble from "https://framerusercontent.com/modules/hwyXKSBSUSfWE0hql0LO/rpUilysupUU2hlE2BlLC/TextScramble.js";
const TextScrambleFonts = getFonts(TextScramble);
const MotionAWithHoverSoundbi2oub = withCodeBoundaryForOverrides(motion.a, {
    nodeId: "UNehzXs8I",
    override: withHoverSound,
    scopeId: "fZZDcLnpx"
});
const enabledGestures = {
    ecK8LU20o: {
        hover: true
    },
    UNehzXs8I: {
        hover: true
    }
};
const cycleOrder = ["UNehzXs8I", "ecK8LU20o"];
const serializationHash = "framer-hYW8a";
const variantClassNames = {
    ecK8LU20o: "framer-v-62e06p",
    UNehzXs8I: "framer-v-bi2oub"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const JFcX5H46A = undefined;
const wBfQBcGBD = undefined;
const kE4aesh2j = undefined;
const transition1 = {
    bounce: 0,
    delay: 0,
    duration: .6,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const humanReadableVariantMap = {
    "icon-left": "UNehzXs8I",
    "icon-right": "ecK8LU20o"
};
const Variants = motion.create(React.Fragment);
const getProps = ({
    color,
    height,
    id,
    link,
    text,
    width,
    ...props
}) => {
    return { ...props,
        JFcX5H46A: link ? ? props.JFcX5H46A,
        kE4aesh2j: text ? ? props.kE4aesh2j ? ? "WORK",
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "UNehzXs8I",
        wBfQBcGBD: color ? ? props.wBfQBcGBD ? ? "var(--token-c0b999b5-d23b-438e-9fb0-60835a3f22f2, rgb(224, 224, 224))"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        kE4aesh2j,
        JFcX5H46A,
        wBfQBcGBD,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "UNehzXs8I",
        enabledGestures,
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsx(Link, {
                    href: JFcX5H46A,
                    motionChild: true,
                    nodeId: "UNehzXs8I",
                    openInNewTab: false,
                    scopeId: "fZZDcLnpx",
                    smoothScroll: true,
                    children: /*#__PURE__*/ _jsxs(MotionAWithHoverSoundbi2oub, { ...restProps,
                        ...gestureHandlers,
                        className: `${cx(scopingClassNames,"framer-bi2oub",className,classNames)} framer-hxdnmm`,
                        "data-framer-name": "icon-left",
                        layoutDependency: layoutDependency,
                        layoutId: "UNehzXs8I",
                        ref: refBinding,
                        style: { ...style
                        },
                        ...addPropertyOverrides({
                            "ecK8LU20o-hover": {
                                "data-framer-name": undefined
                            },
                            "UNehzXs8I-hover": {
                                "data-framer-name": undefined
                            },
                            ecK8LU20o: {
                                "data-framer-name": "icon-right"
                            }
                        }, baseVariant, gestureVariant),
                        children: [ /*#__PURE__*/ _jsx(Instance, {
                            animated: true,
                            className: "framer-1eejrpb",
                            Component: Plus,
                            layoutDependency: layoutDependency,
                            layoutId: "NBQWalgZN",
                            style: {
                                "--43q7um": wBfQBcGBD,
                                rotate: 0
                            },
                            variants: {
                                "ecK8LU20o-hover": {
                                    rotate: 45
                                },
                                "UNehzXs8I-hover": {
                                    rotate: 90
                                }
                            },
                            ...addPropertyOverrides({
                                ecK8LU20o: {
                                    Component: ArrowUpRight
                                }
                            }, baseVariant, gestureVariant)
                        }), /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                            children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                className: "framer-a04vmc-container",
                                "data-code-component-plugin-id": "84d4c1",
                                isAuthoredByUser: true,
                                layoutDependency: layoutDependency,
                                layoutId: "cEkaiftIa-container",
                                nodeId: "cEkaiftIa",
                                rendersWithMotion: true,
                                scopeId: "fZZDcLnpx",
                                children: /*#__PURE__*/ _jsx(TextScramble, {
                                    appearDelay: 0,
                                    characters: "!@#$%^&*()_+-=[]{}|;:,.<>?",
                                    duration: 800,
                                    font: {
                                        fontFamily: '"Geist Mono", monospace',
                                        fontSize: "14px",
                                        fontStyle: "normal",
                                        fontWeight: 400,
                                        letterSpacing: "0.03em",
                                        lineHeight: "1.3em"
                                    },
                                    height: "100%",
                                    id: "cEkaiftIa",
                                    layoutId: "cEkaiftIa",
                                    scrambleIntensity: 100,
                                    text: kE4aesh2j,
                                    textColor: wBfQBcGBD,
                                    triggerMode: "hover",
                                    width: "100%"
                                })
                            })
                        })]
                    })
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-hYW8a.framer-hxdnmm, .framer-hYW8a .framer-hxdnmm { display: block; }", ".framer-hYW8a.framer-bi2oub { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; text-decoration: none; width: min-content; }", ".framer-hYW8a .framer-1eejrpb { flex: none; height: var(--framer-aspect-ratio-supported, 16px); position: relative; width: 16px; }", ".framer-hYW8a .framer-a04vmc-container { flex: none; height: auto; position: relative; width: auto; }", ".framer-hYW8a.framer-v-62e06p .framer-1eejrpb { order: 1; }", ".framer-hYW8a.framer-v-62e06p .framer-a04vmc-container { order: 0; }"];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 18
 * @framerIntrinsicWidth 55.5
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"ecK8LU20o":{"layout":["auto","auto"]},"Et7MpRvuZ":{"layout":["auto","auto"]},"SQeF3ePC1":{"layout":["auto","auto"]}}}
 * @framerVariables {"kE4aesh2j":"text","JFcX5H46A":"link","wBfQBcGBD":"color"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerfZZDcLnpx = withCSS(Component, css, "framer-hYW8a");
export default FramerfZZDcLnpx;
FramerfZZDcLnpx.displayName = "nav-link";
FramerfZZDcLnpx.defaultProps = {
    height: 18,
    width: 55.5
};
addPropertyControls(FramerfZZDcLnpx, {
    variant: {
        options: ["UNehzXs8I", "ecK8LU20o"],
        optionTitles: ["icon-left", "icon-right"],
        title: "Variant",
        type: ControlType.Enum
    },
    kE4aesh2j: {
        defaultValue: "WORK",
        title: "Text",
        type: ControlType.String
    },
    onkE4aesh2jChange: {
        changes: "kE4aesh2j",
        type: ControlType.ChangeHandler
    },
    JFcX5H46A: {
        title: "Link",
        type: ControlType.Link
    },
    wBfQBcGBD: {
        defaultValue: 'var(--token-c0b999b5-d23b-438e-9fb0-60835a3f22f2, rgb(224, 224, 224)) /* {"name":"Off White"} */',
        title: "Color",
        type: ControlType.Color
    }
});
addFonts(FramerfZZDcLnpx, [{
    explicitInter: true,
    fonts: [{
        cssFamilyName: "Geist Mono",
        source: "google",
        style: "normal",
        uiFamilyName: "Geist Mono",
        url: "https://fonts.gstatic.com/s/geistmono/v6/or3yQ6H-1_WfwkMZI_qYPLs1a-t7PU0AbeE9KJ5W7ihaO_CS.woff2",
        weight: "400"
    }]
}, ...TextScrambleFonts], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "reactComponent",
            "name": "FramerfZZDcLnpx",
            "slots": [],
            "annotations": {
                "framerImmutableVariables": "true",
                "framerIntrinsicWidth": "55.5",
                "framerIntrinsicHeight": "18",
                "framerComponentViewportWidth": "true",
                "framerContractVersion": "1",
                "framerVariables": "{\"kE4aesh2j\":\"text\",\"JFcX5H46A\":\"link\",\"wBfQBcGBD\":\"color\"}",
                "framerDisplayContentsDiv": "false",
                "framerAutoSizeImages": "true",
                "framerColorSyntax": "true",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"auto\",\"auto\"]},\"ecK8LU20o\":{\"layout\":[\"auto\",\"auto\"]},\"Et7MpRvuZ\":{\"layout\":[\"auto\",\"auto\"]},\"SQeF3ePC1\":{\"layout\":[\"auto\",\"auto\"]}}}"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}