// Generated by Framer (f353506)
import {
    jsx as _jsx
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
const serializationHash = "framer-1zVk6";
const variantClassNames = {
    ZMr8Qc1dX: "framer-v-zy31sy"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const mK_Oy4r3R = undefined;
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const getProps = ({
    color,
    height,
    id,
    width,
    ...props
}) => {
    return { ...props,
        mK_Oy4r3R: color ? ? props.mK_Oy4r3R ? ? "var(--token-0476634d-d018-44af-ab6c-08b29120481d, rgb(158, 158, 158))"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        mK_Oy4r3R,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        defaultVariant: "ZMr8Qc1dX",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsx(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-zy31sy", className, classNames),
                    "data-framer-name": "Variant 1",
                    layoutDependency: layoutDependency,
                    layoutId: "ZMr8Qc1dX",
                    ref: refBinding,
                    style: {
                        backgroundColor: mK_Oy4r3R,
                        ...style
                    }
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-1zVk6.framer-st7gyq, .framer-1zVk6 .framer-st7gyq { display: block; }", ".framer-1zVk6.framer-zy31sy { height: 1px; overflow: var(--overflow-clip-fallback, clip); position: relative; width: 172px; }"];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 1
 * @framerIntrinsicWidth 172
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]}}}
 * @framerVariables {"mK_Oy4r3R":"color"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FrameruIEkdrDi2 = withCSS(Component, css, "framer-1zVk6");
export default FrameruIEkdrDi2;
FrameruIEkdrDi2.displayName = "line";
FrameruIEkdrDi2.defaultProps = {
    height: 1,
    width: 172
};
addPropertyControls(FrameruIEkdrDi2, {
    mK_Oy4r3R: {
        defaultValue: 'var(--token-0476634d-d018-44af-ab6c-08b29120481d, rgb(158, 158, 158)) /* {"name":"Light Grey"} */',
        title: "Color",
        type: ControlType.Color
    }
});
addFonts(FrameruIEkdrDi2, [{
    explicitInter: true,
    fonts: []
}], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "FrameruIEkdrDi2",
            "slots": [],
            "annotations": {
                "framerVariables": "{\"mK_Oy4r3R\":\"color\"}",
                "framerColorSyntax": "true",
                "framerContractVersion": "1",
                "framerDisplayContentsDiv": "false",
                "framerComponentViewportWidth": "true",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"fixed\"]}}}",
                "framerAutoSizeImages": "true",
                "framerIntrinsicHeight": "1",
                "framerIntrinsicWidth": "172",
                "framerImmutableVariables": "true"
            }
        },
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./uIEkdrDi2.map