// Generated by Framer (3f060d6)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ComponentViewportProvider,
    ControlType,
    cx,
    getFonts,
    SmartComponentScopedContainer,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS,
    withFX,
    withOptimizedAppearEffect
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import GlobeSimple from "https://framerusercontent.com/modules/61SNHA7bRTBw9kWpniCZ/5fY3u3BveuYMQ037vyco/tEf9qevmb.js";
import {
    Time as TimeDate
} from "https://framerusercontent.com/modules/HYcHVPAbe8jLEeU7c4mp/QiycTxX7vdblEOi3o00G/Time.js";
import TextScramble from "https://framerusercontent.com/modules/hwyXKSBSUSfWE0hql0LO/rpUilysupUU2hlE2BlLC/TextScramble.js";
const GlobeSimpleFonts = getFonts(GlobeSimple);
const TextScrambleFonts = getFonts(TextScramble);
const TimeDateFonts = getFonts(TimeDate);
const MotionDivWithFXWithOptimizedAppearEffect = withOptimizedAppearEffect(withFX(motion.div));
const serializationHash = "framer-TOHgl";
const variantClassNames = {
    ANwb9I2jh: "framer-v-1tlhg0k"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const KYsGZ1onb = undefined;
const transition1 = {
    bounce: 0,
    delay: .4,
    duration: .8,
    type: "spring"
};
const animation = {
    opacity: 1,
    rotate: 0,
    rotateX: 0,
    rotateY: 0,
    scale: 1,
    skewX: 0,
    skewY: 0,
    transition: transition1,
    x: 0,
    y: 0
};
const animation1 = {
    opacity: .001,
    rotate: 0,
    rotateX: 0,
    rotateY: 0,
    scale: 1,
    skewX: 0,
    skewY: 0,
    x: 0,
    y: 70
};
const transition2 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const getProps = ({
    color,
    height,
    id,
    width,
    ...props
}) => {
    return { ...props,
        KYsGZ1onb: color ? ? props.KYsGZ1onb ? ? "var(--token-bedfb557-a1ae-48fb-a49c-99449e810c34, rgb(66, 66, 66))"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        KYsGZ1onb,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        defaultVariant: "ANwb9I2jh",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition2,
                children: /*#__PURE__*/ _jsxs(MotionDivWithFXWithOptimizedAppearEffect, { ...restProps,
                    ...gestureHandlers,
                    __framer__presenceAnimate: animation,
                    __framer__presenceInitial: animation1,
                    __perspectiveFX: false,
                    __smartComponentFX: true,
                    __targetOpacity: 1,
                    className: cx(scopingClassNames, "framer-1tlhg0k", className, classNames),
                    "data-framer-appear-id": "1tlhg0k",
                    "data-framer-name": "Variant 1",
                    layoutDependency: layoutDependency,
                    layoutId: "ANwb9I2jh",
                    optimized: true,
                    ref: refBinding,
                    style: { ...style
                    },
                    children: [ /*#__PURE__*/ _jsxs(motion.div, {
                        className: "framer-1ppeozw",
                        layoutDependency: layoutDependency,
                        layoutId: "K7LH5vnWT",
                        children: [ /*#__PURE__*/ _jsx(GlobeSimple, {
                            animated: true,
                            className: "framer-9awosb",
                            layoutDependency: layoutDependency,
                            layoutId: "IaNl2GbBb",
                            style: {
                                "--1m6trwb": 0,
                                "--21h8s6": KYsGZ1onb,
                                "--pgex8v": 1.5
                            }
                        }), /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                            children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                className: "framer-1bdbqlt-container",
                                "data-code-component-plugin-id": "84d4c1",
                                isAuthoredByUser: true,
                                layoutDependency: layoutDependency,
                                layoutId: "O3Dhz9jPS-container",
                                nodeId: "O3Dhz9jPS",
                                rendersWithMotion: true,
                                scopeId: "fNdYSv7_b",
                                children: /*#__PURE__*/ _jsx(TextScramble, {
                                    appearDelay: 5e3,
                                    characters: "!@#$%^&*()_+-=[]{}|;:,.<>?",
                                    duration: 1e3,
                                    font: {
                                        fontFamily: '"Geist Mono", monospace',
                                        fontSize: "14px",
                                        fontStyle: "normal",
                                        fontWeight: 500,
                                        letterSpacing: "0.03em",
                                        lineHeight: "1.3em"
                                    },
                                    height: "100%",
                                    id: "O3Dhz9jPS",
                                    layoutId: "O3Dhz9jPS",
                                    scrambleIntensity: 100,
                                    style: {
                                        maxWidth: "100%"
                                    },
                                    text: "IN",
                                    textColor: KYsGZ1onb,
                                    triggerMode: "appear",
                                    width: "100%"
                                })
                            })
                        })]
                    }), /*#__PURE__*/ _jsxs(motion.div, {
                        className: "framer-146sh9x",
                        layoutDependency: layoutDependency,
                        layoutId: "psN5nQeob",
                        children: [ /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                            children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                className: "framer-odpisc-container",
                                isAuthoredByUser: true,
                                isModuleExternal: true,
                                layoutDependency: layoutDependency,
                                layoutId: "u14Zop5NZ-container",
                                nodeId: "u14Zop5NZ",
                                rendersWithMotion: true,
                                scopeId: "fNdYSv7_b",
                                children: /*#__PURE__*/ _jsx(TimeDate, {
                                    color: KYsGZ1onb,
                                    font: {
                                        fontFamily: '"Geist Mono", monospace',
                                        fontSize: "14px",
                                        fontStyle: "normal",
                                        fontWeight: 400,
                                        letterSpacing: "0.03em",
                                        lineHeight: "1em"
                                    },
                                    height: "100%",
                                    id: "u14Zop5NZ",
                                    layoutId: "u14Zop5NZ",
                                    monthFormat: "long",
                                    outputType: "time",
                                    showMinutes: true,
                                    showMonth: true,
                                    showSeconds: false,
                                    showWeekday: true,
                                    showYear: true,
                                    tabularFont: true,
                                    timeFormat: "24h",
                                    width: "100%"
                                })
                            })
                        }), /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                            children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                className: "framer-ybv8dz-container",
                                "data-code-component-plugin-id": "84d4c1",
                                isAuthoredByUser: true,
                                layoutDependency: layoutDependency,
                                layoutId: "JSpU3vVsX-container",
                                nodeId: "JSpU3vVsX",
                                rendersWithMotion: true,
                                scopeId: "fNdYSv7_b",
                                children: /*#__PURE__*/ _jsx(TextScramble, {
                                    appearDelay: 5e3,
                                    characters: "!@#$%^&*()_+-=[]{}|;:,.<>?",
                                    duration: 1e3,
                                    font: {
                                        fontFamily: '"Geist Mono", monospace',
                                        fontSize: "14px",
                                        fontStyle: "normal",
                                        fontWeight: 500,
                                        letterSpacing: "0.03em",
                                        lineHeight: "1.3em"
                                    },
                                    height: "100%",
                                    id: "JSpU3vVsX",
                                    layoutId: "JSpU3vVsX",
                                    scrambleIntensity: 100,
                                    style: {
                                        maxWidth: "100%"
                                    },
                                    text: "IST",
                                    textColor: KYsGZ1onb,
                                    triggerMode: "appear",
                                    width: "100%"
                                })
                            })
                        })]
                    })]
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-TOHgl.framer-mz3j1b, .framer-TOHgl .framer-mz3j1b { display: block; }", ".framer-TOHgl.framer-1tlhg0k { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }", ".framer-TOHgl .framer-1ppeozw { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }", ".framer-TOHgl .framer-9awosb { flex: none; height: var(--framer-aspect-ratio-supported, 16px); position: relative; width: 16px; }", ".framer-TOHgl .framer-1bdbqlt-container, .framer-TOHgl .framer-ybv8dz-container { flex: none; height: auto; max-width: 256px; position: relative; width: auto; }", ".framer-TOHgl .framer-146sh9x { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }", ".framer-TOHgl .framer-odpisc-container { flex: none; height: auto; position: relative; width: auto; }"];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 40.5
 * @framerIntrinsicWidth 78.5
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","auto"]}}}
 * @framerVariables {"KYsGZ1onb":"color"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerfNdYSv7_b = withCSS(Component, css, "framer-TOHgl");
export default FramerfNdYSv7_b;
FramerfNdYSv7_b.displayName = "timezone";
FramerfNdYSv7_b.defaultProps = {
    height: 40.5,
    width: 78.5
};
addPropertyControls(FramerfNdYSv7_b, {
    KYsGZ1onb: {
        defaultValue: 'var(--token-bedfb557-a1ae-48fb-a49c-99449e810c34, rgb(66, 66, 66)) /* {"name":"Grey"} */',
        title: "Color",
        type: ControlType.Color
    }
});
addFonts(FramerfNdYSv7_b, [{
    explicitInter: true,
    fonts: [{
        cssFamilyName: "Geist Mono",
        source: "google",
        style: "normal",
        uiFamilyName: "Geist Mono",
        url: "https://fonts.gstatic.com/s/geistmono/v6/or3yQ6H-1_WfwkMZI_qYPLs1a-t7PU0AbeEPKJ5W7ihaO_CS.woff2",
        weight: "500"
    }, {
        cssFamilyName: "Geist Mono",
        source: "google",
        style: "normal",
        uiFamilyName: "Geist Mono",
        url: "https://fonts.gstatic.com/s/geistmono/v6/or3yQ6H-1_WfwkMZI_qYPLs1a-t7PU0AbeE9KJ5W7ihaO_CS.woff2",
        weight: "400"
    }]
}, ...GlobeSimpleFonts, ...TextScrambleFonts, ...TimeDateFonts], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "FramerfNdYSv7_b",
            "slots": [],
            "annotations": {
                "framerContractVersion": "1",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"auto\",\"auto\"]}}}",
                "framerComponentViewportWidth": "true",
                "framerAutoSizeImages": "true",
                "framerIntrinsicWidth": "78.5",
                "framerIntrinsicHeight": "40.5",
                "framerColorSyntax": "true",
                "framerVariables": "{\"KYsGZ1onb\":\"color\"}",
                "framerDisplayContentsDiv": "false",
                "framerImmutableVariables": "true"
            }
        },
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./fNdYSv7_b.map